name: Format Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Run pre-commit checks
      run: pre-commit run --all-files
